tasks:
  - name: bundle-install
    init: | 
      bundle install
      gp sync-done bundle-install
  
  - name: server-run
    command: | 
      gp sync-await bundle-install
      sleep 10
      bundle exec ruby server.rb

  - name: 'open-preview'
    command: |
      gp await-port 8080
      gp preview $(gp url 8080)

ports:
  - port: 8080
    onOpen: ignore